#!/bin/sh
# build-release.sh — build a SELF-CONTAINED, relocatable iaragon release.
#
#   ./scripts/build-release.sh [OUTDIR]
#
# The result is a single directory (and a .tar.gz of it) that runs on any
# compatible Linux WITHOUT Erlang, Gleam, rebar3 or a C compiler installed —
# the whole point of "feels like downloading something". It bundles:
#   * the BEAM runtime (ERTS) + the OTP standard library, and
#   * the compiled Gleam application (all dependency ebins + NIFs),
# behind three launchers (iaragon / iaragon-login / iaragon-doctor).
#
# Why this is relocatable (verified against the OTP 29 `erl` script): the
# bundled `otp/bin/erl` derives its ROOTDIR by walking UP from its own path
# until it finds an `erts-<vsn>` sibling (the `find_rootdir` function, whose
# own comment says "It is likely that the files have been copied or moved").
# So invoking the bundled erl by its in-bundle path makes it find the bundled
# OTP — no install step, no hardcoded prefix, no PATH pollution. We also pass
# ERL_ROOTDIR explicitly as a belt-and-braces override.
#
# CONSTRAINT the caller owns: the ERTS and the NIFs (esqlite, fs) are native
# code compiled against THIS machine's libc/arch. The tarball is therefore
# per-(os, arch) and only runs on a target with a compatible-or-newer libc —
# build on the OLDEST glibc you intend to support. The archive name records
# the arch; the OS baseline is the builder's and is the packager's to track.
#
# Env overrides:
#   ERL          erl to source the runtime from (default: first on PATH)
#   GLEAM        gleam binary (default: first on PATH)
#   REL_NAME     archive basename (default: iaragon-<os>-<arch>)
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT_DIR"

ERL="${ERL:-erl}"
GLEAM="${GLEAM:-gleam}"
OUTDIR="${1:-$ROOT_DIR/build/release}"

have() { command -v "$1" >/dev/null 2>&1; }
die()  { echo "error: $1" >&2; exit 1; }
log()  { echo "==> $1"; }

have "$ERL"   || die "erl not found (set ERL=/path/to/erl); a build host needs Erlang, the TARGET will not"
have "$GLEAM" || die "gleam not found (set GLEAM=/path/to/gleam)"

# Source root of the OTP install to bundle (…/erts-*, …/lib, …/bin live here).
OTP_ROOT=$("$ERL" -noshell -eval 'io:format("~s",[code:root_dir()]),halt().')
[ -d "$OTP_ROOT" ] || die "could not resolve the OTP root from '$ERL'"
# Ask the RUNNING erl which ERTS it uses instead of globbing erts-* — an OTP
# root carrying two erts versions (in-place upgrade) would otherwise let the
# alphabetically-first one win, mismatching the version otp/bin/erl hardcodes.
ERTS="erts-$("$ERL" -noshell -eval 'io:format("~s",[erlang:system_info(version)]),halt().')"
[ -d "$OTP_ROOT/$ERTS" ] || die "no $ERTS directory under $OTP_ROOT"

ARCH=$(uname -m)
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
REL_NAME="${REL_NAME:-iaragon-$OS-$ARCH}"
STAGE="$OUTDIR/$REL_NAME"

log "runtime source: $OTP_ROOT ($ERTS)"
log "target archive: $REL_NAME.tar.gz"

# --- compile the Gleam application into an Erlang shipment ------------------
log "compiling (gleam export erlang-shipment)"
"$GLEAM" export erlang-shipment >/dev/null
[ -d build/erlang-shipment ] || die "gleam export produced no build/erlang-shipment"

# --- stage the bundle -------------------------------------------------------
log "staging $STAGE"
rm -rf "$STAGE"
mkdir -p "$STAGE/app" "$STAGE/bin"

# The application: every dependency dir (each carries its own ebin/ + priv/).
# Skip the shipment's own entrypoint scripts — we generate our own launchers
# that point at the bundled erl.
for d in build/erlang-shipment/*/; do
  name=$(basename "$d")
  cp -a "$d" "$STAGE/app/$name"
done

# Apache-2.0 compliance: the tarball redistributes iaragon AND Erlang/OTP
# (both Apache-2.0), so it must carry the license text and the NOTICE.
cp "$ROOT_DIR/LICENSE" "$STAGE/LICENSE"
cp "$ROOT_DIR/NOTICE"  "$STAGE/NOTICE"

# The runtime: erts + the OTP libraries + the root scripts (relocatable).
mkdir -p "$STAGE/otp"
cp -a "$OTP_ROOT/$ERTS" "$STAGE/otp/$ERTS"
cp -a "$OTP_ROOT/lib"   "$STAGE/otp/lib"
cp -a "$OTP_ROOT/bin"   "$STAGE/otp/bin"
[ -d "$OTP_ROOT/releases" ] && cp -a "$OTP_ROOT/releases" "$STAGE/otp/releases" || true
[ -d "$OTP_ROOT/usr" ]      && cp -a "$OTP_ROOT/usr"      "$STAGE/otp/usr"      || true

# --- launchers --------------------------------------------------------------
# Each resolves the bundle root from its own location, so the bundle runs from
# wherever it is extracted. ERL_ROOTDIR pins the runtime to the bundled OTP.
emit_launcher() { # file  eval-expr  [extra-flags-before-eval]
  cat > "$STAGE/bin/$1" <<EOF
#!/bin/sh
# iaragon launcher (generated by build-release.sh) — self-contained.
set -eu
HERE=\$(CDPATH= cd -- "\$(dirname -- "\$0")" && pwd)
ROOT=\$(dirname "\$HERE")
export ERL_ROOTDIR="\$ROOT/otp"
exec "\$ROOT/otp/bin/erl" \\
  -pa "\$ROOT"/app/*/ebin \\
  -noshell \\
  $3 \\
  -eval '$2' \\
  -extra "\$@"
EOF
  chmod +x "$STAGE/bin/$1"
}

# The daemon runs the Gleam main and blocks; the -eval convention matches the
# shipment's own entrypoint (iaragon@@main:run(iaragon)).
emit_launcher iaragon        'iaragon@@main:run(iaragon)' ''
emit_launcher iaragon-login  'iaragon@login:main(), halt(0)' ''
emit_launcher iaragon-doctor 'iaragon@doctor:main(), halt(0)' ''

# --- archive ----------------------------------------------------------------
log "packing"
( cd "$OUTDIR" && tar czf "$REL_NAME.tar.gz" "$REL_NAME" )

SIZE=$(du -sh "$OUTDIR/$REL_NAME.tar.gz" | cut -f1)
cat <<EOF

==> built $OUTDIR/$REL_NAME.tar.gz ($SIZE)

  Extract anywhere and run — no Erlang/Gleam/rebar3/gcc required on the target:
    tar xzf $REL_NAME.tar.gz
    ./$REL_NAME/bin/iaragon-login     # one-time OAuth login
    ./$REL_NAME/bin/iaragon           # the daemon
    ./$REL_NAME/bin/iaragon-doctor    # health check
EOF
